# Generated by Django 4.0.6 on 2022-07-22 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import library_store.utils.models_ids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.CharField(default=library_store.utils.models_ids.get_book_id, max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(max_length=50)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('BORROWED', 'BORROWED'), ('NOT_AVAILABLE', 'NOT_AVAILABLE')], default='AVAILABLE', max_length=50)),
                ('is_removed', models.BooleanField(default=False)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LIBRARIAN', 'LIBRARIAN'), ('MEMBER', 'MEMBER')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookBorrowDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date_time', models.DateTimeField(auto_now=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('returned_date_time', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_store.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
