# Generated by Django 4.0.6 on 2022-07-21 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import library_store.utils.models_ids


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(default=library_store.utils.models_ids.get_book_id, max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.CharField(max_length=50)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'AVAILABLE'), ('BORROWED', 'BORROWED'), ('NOT_AVAILABLE', 'NOT_AVAILABLE')], default='AVAILABLE', max_length=50)),
                ('borrowed_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
