# Generated by Django 4.0.6 on 2022-07-21 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_store', '0002_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='borrowed_by_user',
            new_name='created_by_user',
        ),
        migrations.AddField(
            model_name='book',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserBookBorrowDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date_time', models.DateTimeField()),
                ('is_returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_store.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
