# Generated by Django 4.0.6 on 2022-07-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_store', '0003_rename_borrowed_by_user_book_created_by_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id',
            new_name='book_id',
        ),
        migrations.AddField(
            model_name='userbookborrowdetails',
            name='returned_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='userbookborrowdetails',
            name='borrowed_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
