# Generated by Django 4.0.6 on 2022-07-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_store', '0004_rename_id_book_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
